# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\"*\n\x08Mensagem\x12\x0c\n\x04\x64ono\x18\x01 \x01(\t\x12\x10\n\x08\x63onteudo\x18\x02 \x01(\t\"\t\n\x07Retorno2S\n\x04\x43hat\x12%\n\x0c\x43onversaChat\x12\x08.Retorno\x1a\t.Mensagem0\x01\x12$\n\rEnviaMensagem\x12\t.Mensagem\x1a\x08.Retornob\x06proto3')



_MENSAGEM = DESCRIPTOR.message_types_by_name['Mensagem']
_RETORNO = DESCRIPTOR.message_types_by_name['Retorno']
Mensagem = _reflection.GeneratedProtocolMessageType('Mensagem', (_message.Message,), {
  'DESCRIPTOR' : _MENSAGEM,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:Mensagem)
  })
_sym_db.RegisterMessage(Mensagem)

Retorno = _reflection.GeneratedProtocolMessageType('Retorno', (_message.Message,), {
  'DESCRIPTOR' : _RETORNO,
  '__module__' : 'chat_pb2'
  # @@protoc_insertion_point(class_scope:Retorno)
  })
_sym_db.RegisterMessage(Retorno)

_CHAT = DESCRIPTOR.services_by_name['Chat']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MENSAGEM._serialized_start=14
  _MENSAGEM._serialized_end=56
  _RETORNO._serialized_start=58
  _RETORNO._serialized_end=67
  _CHAT._serialized_start=69
  _CHAT._serialized_end=152
# @@protoc_insertion_point(module_scope)
